import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { SymbolWeight, SymbolViewProps } from "expo-symbols";
import { ComponentProps } from "react";
import { OpaqueColorValue, type StyleProp, type TextStyle } from "react-native";

type IconMapping = Record<SymbolViewProps["name"], ComponentProps<typeof MaterialIcons>["name"]>;
type IconSymbolName = keyof typeof MAPPING;

const MAPPING = {
  "house.fill": "home",
  "paperplane.fill": "send",
  "chevron.left.forwardslash.chevron.right": "code",
  "chevron.right": "chevron-right",
  "chevron.left": "chevron-left",
  "chevron.down": "expand-more",
  "chevron.up": "expand-less",
  "list.bullet": "format-list-bulleted",
  "storefront.fill": "store",
  "tag.fill": "local-offer",
  "gearshape.fill": "settings",
  "location.fill": "location-on",
  "map.fill": "map",
  "plus.circle.fill": "add-circle",
  "plus": "add",
  "trash.fill": "delete",
  "checkmark": "check",
  "xmark.circle.fill": "cancel",
  "xmark": "close",
  "magnifyingglass": "search",
  "crown.fill": "workspace-premium",
  "globe": "language",
  "star.fill": "star",
  "star": "star-outline",
  "bell.fill": "notifications",
  "bell": "notifications-none",
  "camera.fill": "camera-alt",
  "photo.fill": "photo",
  "barcode.viewfinder": "qr-code-scanner",
  "doc.text.fill": "description",
  "arrow.up.circle.fill": "upload",
  "info.circle.fill": "info",
  "person.fill": "person",
  "gift.fill": "card-giftcard",
  "link": "link",
  "checkmark.circle.fill": "check-circle",
  "checkmark.circle": "check-circle-outline",
  "square.and.arrow.up": "share",
  "mic.fill": "mic",
  "mic": "mic-none",
  "waveform": "graphic-eq",
  "cart.fill": "shopping-cart",
  "cart": "shopping-cart",
  "creditcard.fill": "credit-card",
  "creditcard": "credit-card",
  "wallet.pass.fill": "account-balance-wallet",
  "dollarsign.circle.fill": "monetization-on",
  "dollarsign.circle": "attach-money",
  "chart.bar.fill": "bar-chart",
  "chart.line.uptrend.xyaxis": "trending-up",
  "chart.pie.fill": "pie-chart",
  "fork.knife": "restaurant",
  "fork.knife.circle.fill": "restaurant",
  "calendar": "calendar-today",
  "calendar.badge.plus": "event",
  "clock.fill": "access-time",
  "clock": "access-time",
  "timer": "timer",
  "trophy.fill": "emoji-events",
  "flame.fill": "local-fire-department",
  "bolt.fill": "bolt",
  "leaf.fill": "eco",
  "heart.fill": "favorite",
  "heart": "favorite-border",
  "bookmark.fill": "bookmark",
  "bookmark": "bookmark-border",
  "pencil": "edit",
  "pencil.circle.fill": "edit",
  "arrow.clockwise": "refresh",
  "arrow.left": "arrow-back",
  "arrow.right": "arrow-forward",
  "arrow.up": "arrow-upward",
  "arrow.down": "arrow-downward",
  "arrow.down.circle.fill": "download",
  "square.and.pencil": "edit-note",
  "doc.fill": "insert-drive-file",
  "doc.badge.plus": "note-add",
  "printer.fill": "print",
  "envelope.fill": "email",
  "phone.fill": "phone",
  "ellipsis": "more-horiz",
  "ellipsis.circle": "more-horiz",
  "slider.horizontal.3": "tune",
  "line.3.horizontal": "menu",
  "line.3.horizontal.decrease.circle": "filter-list",
  "arrow.up.arrow.down": "swap-vert",
  "repeat": "repeat",
  "shuffle": "shuffle",
  "eye.fill": "visibility",
  "eye.slash.fill": "visibility-off",
  "lock.fill": "lock",
  "lock.open.fill": "lock-open",
  "exclamationmark.triangle.fill": "warning",
  "exclamationmark.circle.fill": "error",
  "questionmark.circle.fill": "help",
  "hand.thumbsup.fill": "thumb-up",
  "sparkles": "auto-awesome",
  "wand.and.stars": "auto-fix-high",
  "rectangle.stack.fill": "layers",
  "square.grid.2x2.fill": "grid-view",
  "list.dash": "format-list-bulleted",
  "bag.fill": "shopping-bag",
  "percent": "percent",
  "scissors": "content-cut",
  "barcode": "barcode-reader",
  "qrcode": "qr-code",
  "photo.on.rectangle": "add-photo-alternate",
  "arrow.triangle.2.circlepath": "sync",
  "icloud.fill": "cloud",
  "wifi": "wifi",
  "location.slash.fill": "location-off",
  "mappin.circle.fill": "place",
  "mappin": "place",
  "scope": "my-location",
} as IconMapping;

export function IconSymbol({
  name,
  size = 24,
  color,
  style,
}: {
  name: IconSymbolName;
  size?: number;
  color: string | OpaqueColorValue;
  style?: StyleProp<TextStyle>;
  weight?: SymbolWeight;
}) {
  return <MaterialIcons color={color} size={size} name={MAPPING[name]} style={style} />;
}
