#!/usr/bin/env python3
"""Add all remaining missing i18n keys to locale files."""
import json, os

LOCALES_DIR = "/home/ubuntu/belief-field-detector/lib/i18n/locales"

# Keys to add per section per language
ADDITIONS = {
    "en": {
        "common": {
            "tryAgain": "Try Again",
        },
        "coupons": {
            "scan": "Scan",
            "saved": "{{count}} saved",
            "added": "Added",
            "coupon": "Coupon",
            "noCoupons": "No coupons saved",
            "noCouponsSubtitlePremium": "Scan or import coupon images to save them here.",
            "noCouponsSubtitleFree": "Upgrade to Premium to save and organize your coupons.",
            "premiumFeature": "Premium Feature",
            "upsellDesc": "Save and organize coupons from your camera or photo library. Upgrade to Premium to unlock.",
            "cameraPermission": "Camera Permission",
            "cameraPermissionMessage": "Camera access is required to scan coupons.",
            "saveFailed": "Failed to save coupon.",
            "deleteConfirm": "Remove this coupon?",
        },
        "settings": {
            "geofencing": "Geofencing",
        },
        "list": {
            "confirmClearButton": "Remove",
            "title": "items",
        },
    },
    "es": {
        "common": {"tryAgain": "Intentar de nuevo"},
        "coupons": {
            "scan": "Escanear",
            "saved": "{{count}} guardados",
            "added": "Agregado",
            "coupon": "Cupón",
            "noCoupons": "No hay cupones guardados",
            "noCouponsSubtitlePremium": "Escanea o importa imágenes de cupones para guardarlos aquí.",
            "noCouponsSubtitleFree": "Actualiza a Premium para guardar y organizar tus cupones.",
            "premiumFeature": "Función Premium",
            "upsellDesc": "Guarda y organiza cupones desde tu cámara o biblioteca de fotos. Actualiza a Premium para desbloquear.",
            "cameraPermission": "Permiso de Cámara",
            "cameraPermissionMessage": "Se requiere acceso a la cámara para escanear cupones.",
            "saveFailed": "Error al guardar el cupón.",
            "deleteConfirm": "¿Eliminar este cupón?",
        },
        "settings": {"geofencing": "Geofencing"},
        "list": {"confirmClearButton": "Eliminar", "title": "artículos"},
    },
    "fr": {
        "common": {"tryAgain": "Réessayer"},
        "coupons": {
            "scan": "Scanner",
            "saved": "{{count}} sauvegardés",
            "added": "Ajouté",
            "coupon": "Coupon",
            "noCoupons": "Aucun coupon sauvegardé",
            "noCouponsSubtitlePremium": "Scannez ou importez des images de coupons pour les sauvegarder ici.",
            "noCouponsSubtitleFree": "Passez à Premium pour sauvegarder et organiser vos coupons.",
            "premiumFeature": "Fonctionnalité Premium",
            "upsellDesc": "Sauvegardez et organisez les coupons depuis votre appareil photo ou bibliothèque. Passez à Premium pour débloquer.",
            "cameraPermission": "Permission Caméra",
            "cameraPermissionMessage": "L'accès à la caméra est requis pour scanner les coupons.",
            "saveFailed": "Échec de la sauvegarde du coupon.",
            "deleteConfirm": "Supprimer ce coupon?",
        },
        "settings": {"geofencing": "Géofencing"},
        "list": {"confirmClearButton": "Supprimer", "title": "articles"},
    },
    "de": {
        "common": {"tryAgain": "Erneut versuchen"},
        "coupons": {
            "scan": "Scannen",
            "saved": "{{count}} gespeichert",
            "added": "Hinzugefügt",
            "coupon": "Gutschein",
            "noCoupons": "Keine Gutscheine gespeichert",
            "noCouponsSubtitlePremium": "Scannen oder importieren Sie Gutscheinbilder, um sie hier zu speichern.",
            "noCouponsSubtitleFree": "Upgrade auf Premium, um Gutscheine zu speichern und zu organisieren.",
            "premiumFeature": "Premium-Funktion",
            "upsellDesc": "Speichern und organisieren Sie Gutscheine von Ihrer Kamera oder Fotobibliothek. Upgrade auf Premium zum Entsperren.",
            "cameraPermission": "Kameraberechtigung",
            "cameraPermissionMessage": "Kamerazugriff ist erforderlich, um Gutscheine zu scannen.",
            "saveFailed": "Gutschein konnte nicht gespeichert werden.",
            "deleteConfirm": "Diesen Gutschein entfernen?",
        },
        "settings": {"geofencing": "Geofencing"},
        "list": {"confirmClearButton": "Entfernen", "title": "Artikel"},
    },
    "pt": {
        "common": {"tryAgain": "Tentar novamente"},
        "coupons": {
            "scan": "Escanear",
            "saved": "{{count}} salvos",
            "added": "Adicionado",
            "coupon": "Cupom",
            "noCoupons": "Nenhum cupom salvo",
            "noCouponsSubtitlePremium": "Escaneie ou importe imagens de cupons para salvá-los aqui.",
            "noCouponsSubtitleFree": "Atualize para Premium para salvar e organizar seus cupons.",
            "premiumFeature": "Recurso Premium",
            "upsellDesc": "Salve e organize cupons da sua câmera ou biblioteca de fotos. Atualize para Premium para desbloquear.",
            "cameraPermission": "Permissão de Câmera",
            "cameraPermissionMessage": "O acesso à câmera é necessário para escanear cupons.",
            "saveFailed": "Falha ao salvar cupom.",
            "deleteConfirm": "Remover este cupom?",
        },
        "settings": {"geofencing": "Geofencing"},
        "list": {"confirmClearButton": "Remover", "title": "itens"},
    },
    "it": {
        "common": {"tryAgain": "Riprova"},
        "coupons": {
            "scan": "Scansiona",
            "saved": "{{count}} salvati",
            "added": "Aggiunto",
            "coupon": "Coupon",
            "noCoupons": "Nessun coupon salvato",
            "noCouponsSubtitlePremium": "Scansiona o importa immagini di coupon per salvarli qui.",
            "noCouponsSubtitleFree": "Passa a Premium per salvare e organizzare i tuoi coupon.",
            "premiumFeature": "Funzione Premium",
            "upsellDesc": "Salva e organizza coupon dalla fotocamera o dalla libreria foto. Passa a Premium per sbloccare.",
            "cameraPermission": "Permesso Fotocamera",
            "cameraPermissionMessage": "L'accesso alla fotocamera è necessario per scansionare i coupon.",
            "saveFailed": "Impossibile salvare il coupon.",
            "deleteConfirm": "Rimuovere questo coupon?",
        },
        "settings": {"geofencing": "Geofencing"},
        "list": {"confirmClearButton": "Rimuovi", "title": "articoli"},
    },
    "ja": {
        "common": {"tryAgain": "もう一度試す"},
        "coupons": {
            "scan": "スキャン",
            "saved": "{{count}}件保存済み",
            "added": "追加日",
            "coupon": "クーポン",
            "noCoupons": "クーポンが保存されていません",
            "noCouponsSubtitlePremium": "クーポン画像をスキャンまたはインポートして保存してください。",
            "noCouponsSubtitleFree": "クーポンを保存・整理するにはプレミアムにアップグレードしてください。",
            "premiumFeature": "プレミアム機能",
            "upsellDesc": "カメラやフォトライブラリからクーポンを保存・整理できます。プレミアムにアップグレードしてロック解除。",
            "cameraPermission": "カメラの許可",
            "cameraPermissionMessage": "クーポンをスキャンするにはカメラへのアクセスが必要です。",
            "saveFailed": "クーポンの保存に失敗しました。",
            "deleteConfirm": "このクーポンを削除しますか？",
        },
        "settings": {"geofencing": "ジオフェンシング"},
        "list": {"confirmClearButton": "削除", "title": "アイテム"},
    },
    "ko": {
        "common": {"tryAgain": "다시 시도"},
        "coupons": {
            "scan": "스캔",
            "saved": "{{count}}개 저장됨",
            "added": "추가됨",
            "coupon": "쿠폰",
            "noCoupons": "저장된 쿠폰 없음",
            "noCouponsSubtitlePremium": "쿠폰 이미지를 스캔하거나 가져와서 여기에 저장하세요.",
            "noCouponsSubtitleFree": "쿠폰을 저장하고 정리하려면 프리미엄으로 업그레이드하세요.",
            "premiumFeature": "프리미엄 기능",
            "upsellDesc": "카메라나 사진 라이브러리에서 쿠폰을 저장하고 정리하세요. 프리미엄으로 업그레이드하여 잠금 해제.",
            "cameraPermission": "카메라 권한",
            "cameraPermissionMessage": "쿠폰을 스캔하려면 카메라 접근이 필요합니다.",
            "saveFailed": "쿠폰 저장에 실패했습니다.",
            "deleteConfirm": "이 쿠폰을 삭제하시겠습니까?",
        },
        "settings": {"geofencing": "지오펜싱"},
        "list": {"confirmClearButton": "삭제", "title": "항목"},
    },
    "zh": {
        "common": {"tryAgain": "再试一次"},
        "coupons": {
            "scan": "扫描",
            "saved": "已保存{{count}}张",
            "added": "添加于",
            "coupon": "优惠券",
            "noCoupons": "没有保存的优惠券",
            "noCouponsSubtitlePremium": "扫描或导入优惠券图片以保存在此处。",
            "noCouponsSubtitleFree": "升级到高级版以保存和整理您的优惠券。",
            "premiumFeature": "高级功能",
            "upsellDesc": "从相机或照片库保存和整理优惠券。升级到高级版以解锁。",
            "cameraPermission": "相机权限",
            "cameraPermissionMessage": "扫描优惠券需要相机访问权限。",
            "saveFailed": "保存优惠券失败。",
            "deleteConfirm": "删除此优惠券？",
        },
        "settings": {"geofencing": "地理围栏"},
        "list": {"confirmClearButton": "删除", "title": "商品"},
    },
    "ar": {
        "common": {"tryAgain": "حاول مرة أخرى"},
        "coupons": {
            "scan": "مسح",
            "saved": "{{count}} محفوظ",
            "added": "تمت الإضافة",
            "coupon": "كوبون",
            "noCoupons": "لا توجد كوبونات محفوظة",
            "noCouponsSubtitlePremium": "امسح أو استورد صور الكوبونات لحفظها هنا.",
            "noCouponsSubtitleFree": "قم بالترقية إلى Premium لحفظ وتنظيم كوبوناتك.",
            "premiumFeature": "ميزة مميزة",
            "upsellDesc": "احفظ ونظم الكوبونات من الكاميرا أو مكتبة الصور. قم بالترقية إلى Premium للفتح.",
            "cameraPermission": "إذن الكاميرا",
            "cameraPermissionMessage": "مطلوب الوصول إلى الكاميرا لمسح الكوبونات.",
            "saveFailed": "فشل حفظ الكوبون.",
            "deleteConfirm": "إزالة هذا الكوبون؟",
        },
        "settings": {"geofencing": "السياج الجغرافي"},
        "list": {"confirmClearButton": "إزالة", "title": "عناصر"},
    },
    "hi": {
        "common": {"tryAgain": "फिर से प्रयास करें"},
        "coupons": {
            "scan": "स्कैन करें",
            "saved": "{{count}} सहेजे गए",
            "added": "जोड़ा गया",
            "coupon": "कूपन",
            "noCoupons": "कोई कूपन सहेजा नहीं गया",
            "noCouponsSubtitlePremium": "कूपन छवियों को स्कैन या आयात करें।",
            "noCouponsSubtitleFree": "अपने कूपन सहेजने के लिए प्रीमियम में अपग्रेड करें।",
            "premiumFeature": "प्रीमियम सुविधा",
            "upsellDesc": "अपने कैमरे या फोटो लाइब्रेरी से कूपन सहेजें और व्यवस्थित करें।",
            "cameraPermission": "कैमरा अनुमति",
            "cameraPermissionMessage": "कूपन स्कैन करने के लिए कैमरा एक्सेस आवश्यक है।",
            "saveFailed": "कूपन सहेजने में विफल।",
            "deleteConfirm": "यह कूपन हटाएं?",
        },
        "settings": {"geofencing": "जियोफेंसिंग"},
        "list": {"confirmClearButton": "हटाएं", "title": "आइटम"},
    },
    "ru": {
        "common": {"tryAgain": "Попробовать снова"},
        "coupons": {
            "scan": "Сканировать",
            "saved": "{{count}} сохранено",
            "added": "Добавлено",
            "coupon": "Купон",
            "noCoupons": "Купоны не сохранены",
            "noCouponsSubtitlePremium": "Сканируйте или импортируйте изображения купонов для сохранения.",
            "noCouponsSubtitleFree": "Обновитесь до Premium для сохранения и организации купонов.",
            "premiumFeature": "Функция Premium",
            "upsellDesc": "Сохраняйте и организуйте купоны с камеры или фотобиблиотеки. Обновитесь до Premium.",
            "cameraPermission": "Разрешение камеры",
            "cameraPermissionMessage": "Для сканирования купонов требуется доступ к камере.",
            "saveFailed": "Не удалось сохранить купон.",
            "deleteConfirm": "Удалить этот купон?",
        },
        "settings": {"geofencing": "Геофенсинг"},
        "list": {"confirmClearButton": "Удалить", "title": "товаров"},
    },
    "tr": {
        "common": {"tryAgain": "Tekrar dene"},
        "coupons": {
            "scan": "Tara",
            "saved": "{{count}} kaydedildi",
            "added": "Eklendi",
            "coupon": "Kupon",
            "noCoupons": "Kayıtlı kupon yok",
            "noCouponsSubtitlePremium": "Kuponları buraya kaydetmek için tara veya içe aktar.",
            "noCouponsSubtitleFree": "Kuponları kaydetmek için Premium'a yükseltin.",
            "premiumFeature": "Premium Özellik",
            "upsellDesc": "Kameranızdan veya fotoğraf kitaplığından kuponları kaydedin ve düzenleyin.",
            "cameraPermission": "Kamera İzni",
            "cameraPermissionMessage": "Kupon taramak için kamera erişimi gereklidir.",
            "saveFailed": "Kupon kaydedilemedi.",
            "deleteConfirm": "Bu kuponu kaldır?",
        },
        "settings": {"geofencing": "Coğrafi Sınır"},
        "list": {"confirmClearButton": "Kaldır", "title": "ürün"},
    },
    "pl": {
        "common": {"tryAgain": "Spróbuj ponownie"},
        "coupons": {
            "scan": "Skanuj",
            "saved": "{{count}} zapisanych",
            "added": "Dodano",
            "coupon": "Kupon",
            "noCoupons": "Brak zapisanych kuponów",
            "noCouponsSubtitlePremium": "Skanuj lub importuj obrazy kuponów, aby je tutaj zapisać.",
            "noCouponsSubtitleFree": "Zaktualizuj do Premium, aby zapisywać i organizować kupony.",
            "premiumFeature": "Funkcja Premium",
            "upsellDesc": "Zapisuj i organizuj kupony z aparatu lub biblioteki zdjęć.",
            "cameraPermission": "Uprawnienie do aparatu",
            "cameraPermissionMessage": "Dostęp do aparatu jest wymagany do skanowania kuponów.",
            "saveFailed": "Nie udało się zapisać kuponu.",
            "deleteConfirm": "Usunąć ten kupon?",
        },
        "settings": {"geofencing": "Geofencing"},
        "list": {"confirmClearButton": "Usuń", "title": "produktów"},
    },
    "sv": {
        "common": {"tryAgain": "Försök igen"},
        "coupons": {
            "scan": "Skanna",
            "saved": "{{count}} sparade",
            "added": "Tillagd",
            "coupon": "Kupong",
            "noCoupons": "Inga kuponger sparade",
            "noCouponsSubtitlePremium": "Skanna eller importera kupongbilder för att spara dem här.",
            "noCouponsSubtitleFree": "Uppgradera till Premium för att spara och organisera dina kuponger.",
            "premiumFeature": "Premiumfunktion",
            "upsellDesc": "Spara och organisera kuponger från kameran eller fotobiblioteket.",
            "cameraPermission": "Kamerabehörighet",
            "cameraPermissionMessage": "Kameraåtkomst krävs för att skanna kuponger.",
            "saveFailed": "Det gick inte att spara kupongen.",
            "deleteConfirm": "Ta bort den här kupongen?",
        },
        "settings": {"geofencing": "Geofencing"},
        "list": {"confirmClearButton": "Ta bort", "title": "varor"},
    },
    "nl": {
        "common": {"tryAgain": "Opnieuw proberen"},
        "coupons": {
            "scan": "Scannen",
            "saved": "{{count}} opgeslagen",
            "added": "Toegevoegd",
            "coupon": "Coupon",
            "noCoupons": "Geen coupons opgeslagen",
            "noCouponsSubtitlePremium": "Scan of importeer couponafbeeldingen om ze hier op te slaan.",
            "noCouponsSubtitleFree": "Upgrade naar Premium om coupons op te slaan en te organiseren.",
            "premiumFeature": "Premium Functie",
            "upsellDesc": "Sla coupons op en organiseer ze vanuit uw camera of fotobibliotheek.",
            "cameraPermission": "Cameramachtiging",
            "cameraPermissionMessage": "Cameratoegang is vereist om coupons te scannen.",
            "saveFailed": "Coupon opslaan mislukt.",
            "deleteConfirm": "Deze coupon verwijderen?",
        },
        "settings": {"geofencing": "Geofencing"},
        "list": {"confirmClearButton": "Verwijderen", "title": "artikelen"},
    },
    "id": {
        "common": {"tryAgain": "Coba lagi"},
        "coupons": {
            "scan": "Pindai",
            "saved": "{{count}} tersimpan",
            "added": "Ditambahkan",
            "coupon": "Kupon",
            "noCoupons": "Tidak ada kupon tersimpan",
            "noCouponsSubtitlePremium": "Pindai atau impor gambar kupon untuk menyimpannya di sini.",
            "noCouponsSubtitleFree": "Upgrade ke Premium untuk menyimpan dan mengatur kupon Anda.",
            "premiumFeature": "Fitur Premium",
            "upsellDesc": "Simpan dan atur kupon dari kamera atau perpustakaan foto Anda.",
            "cameraPermission": "Izin Kamera",
            "cameraPermissionMessage": "Akses kamera diperlukan untuk memindai kupon.",
            "saveFailed": "Gagal menyimpan kupon.",
            "deleteConfirm": "Hapus kupon ini?",
        },
        "settings": {"geofencing": "Geofencing"},
        "list": {"confirmClearButton": "Hapus", "title": "item"},
    },
    "th": {
        "common": {"tryAgain": "ลองอีกครั้ง"},
        "coupons": {
            "scan": "สแกน",
            "saved": "บันทึกแล้ว {{count}} รายการ",
            "added": "เพิ่มเมื่อ",
            "coupon": "คูปอง",
            "noCoupons": "ไม่มีคูปองที่บันทึกไว้",
            "noCouponsSubtitlePremium": "สแกนหรือนำเข้ารูปภาพคูปองเพื่อบันทึกที่นี่",
            "noCouponsSubtitleFree": "อัปเกรดเป็น Premium เพื่อบันทึกและจัดระเบียบคูปองของคุณ",
            "premiumFeature": "คุณสมบัติพรีเมียม",
            "upsellDesc": "บันทึกและจัดระเบียบคูปองจากกล้องหรือคลังภาพของคุณ",
            "cameraPermission": "สิทธิ์กล้อง",
            "cameraPermissionMessage": "ต้องการการเข้าถึงกล้องเพื่อสแกนคูปอง",
            "saveFailed": "บันทึกคูปองไม่สำเร็จ",
            "deleteConfirm": "ลบคูปองนี้?",
        },
        "settings": {"geofencing": "ขอบเขตภูมิศาสตร์"},
        "list": {"confirmClearButton": "ลบ", "title": "รายการ"},
    },
    "vi": {
        "common": {"tryAgain": "Thử lại"},
        "coupons": {
            "scan": "Quét",
            "saved": "{{count}} đã lưu",
            "added": "Đã thêm",
            "coupon": "Phiếu giảm giá",
            "noCoupons": "Chưa có phiếu giảm giá nào được lưu",
            "noCouponsSubtitlePremium": "Quét hoặc nhập hình ảnh phiếu giảm giá để lưu ở đây.",
            "noCouponsSubtitleFree": "Nâng cấp lên Premium để lưu và tổ chức phiếu giảm giá của bạn.",
            "premiumFeature": "Tính năng Premium",
            "upsellDesc": "Lưu và tổ chức phiếu giảm giá từ máy ảnh hoặc thư viện ảnh của bạn.",
            "cameraPermission": "Quyền Camera",
            "cameraPermissionMessage": "Cần quyền truy cập camera để quét phiếu giảm giá.",
            "saveFailed": "Lưu phiếu giảm giá thất bại.",
            "deleteConfirm": "Xóa phiếu giảm giá này?",
        },
        "settings": {"geofencing": "Địa lý ảo"},
        "list": {"confirmClearButton": "Xóa", "title": "mặt hàng"},
    },
    "el": {
        "common": {"tryAgain": "Δοκιμάστε ξανά"},
        "coupons": {
            "scan": "Σάρωση",
            "saved": "{{count}} αποθηκευμένα",
            "added": "Προστέθηκε",
            "coupon": "Κουπόνι",
            "noCoupons": "Δεν υπάρχουν αποθηκευμένα κουπόνια",
            "noCouponsSubtitlePremium": "Σαρώστε ή εισαγάγετε εικόνες κουπονιών για αποθήκευση.",
            "noCouponsSubtitleFree": "Αναβαθμίστε σε Premium για αποθήκευση και οργάνωση κουπονιών.",
            "premiumFeature": "Λειτουργία Premium",
            "upsellDesc": "Αποθηκεύστε και οργανώστε κουπόνια από την κάμερα ή τη βιβλιοθήκη φωτογραφιών σας.",
            "cameraPermission": "Άδεια Κάμερας",
            "cameraPermissionMessage": "Απαιτείται πρόσβαση στην κάμερα για σάρωση κουπονιών.",
            "saveFailed": "Αποτυχία αποθήκευσης κουπονιού.",
            "deleteConfirm": "Αφαίρεση αυτού του κουπονιού;",
        },
        "settings": {"geofencing": "Γεωφράκτης"},
        "list": {"confirmClearButton": "Αφαίρεση", "title": "αντικείμενα"},
    },
    "he": {
        "common": {"tryAgain": "נסה שוב"},
        "coupons": {
            "scan": "סרוק",
            "saved": "{{count}} שמורים",
            "added": "נוסף",
            "coupon": "קופון",
            "noCoupons": "אין קופונים שמורים",
            "noCouponsSubtitlePremium": "סרוק או ייבא תמונות קופונים כדי לשמור אותם כאן.",
            "noCouponsSubtitleFree": "שדרג ל-Premium כדי לשמור ולארגן את הקופונים שלך.",
            "premiumFeature": "תכונה פרמיום",
            "upsellDesc": "שמור וארגן קופונים מהמצלמה או ספריית התמונות שלך.",
            "cameraPermission": "הרשאת מצלמה",
            "cameraPermissionMessage": "נדרשת גישה למצלמה לסריקת קופונים.",
            "saveFailed": "שמירת הקופון נכשלה.",
            "deleteConfirm": "להסיר קופון זה?",
        },
        "settings": {"geofencing": "גיאו-גדר"},
        "list": {"confirmClearButton": "הסר", "title": "פריטים"},
    },
}

def update_locale_file(lang_code, additions):
    filepath = os.path.join(LOCALES_DIR, f"{lang_code}.json")
    if not os.path.exists(filepath):
        print(f"  SKIP: {filepath} not found")
        return

    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)

    lang_additions = additions.get(lang_code, additions.get("en", {}))
    for section, keys in lang_additions.items():
        if section not in data:
            data[section] = {}
        for key, value in keys.items():
            data[section][key] = value

    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print(f"  Updated: {lang_code}.json")

locale_files = [f.replace(".json", "") for f in os.listdir(LOCALES_DIR) if f.endswith(".json")]
print(f"Found {len(locale_files)} locale files")

for lang in locale_files:
    update_locale_file(lang, ADDITIONS)

print("\nDone!")
